### ISSUE TITLE
What is the purpose of Swarm simulator.cpp ?

### ISSUE THREAD

**Issue by ktiwari9** [Swarm-IITKgp/swarm-gazebo-simulator#20]
Hi there,
I am looking for some example code that can allow me to spawn an obstacle in gazebo using a ros node. Is this the purpose of the Swarm Simulator .cpp ? I just want to show a cylinder at a specific location , where the location is set by the ros node and not manually set by the user during the simulation. Any suggestions on how I can do this ?

**Comment by sam17** [comment]
Use 
rosrun gazebo spawn_model -file `pwd`/object.urdf -urdf -z 1 -model my_object

Source : http://wiki.ros.org/simulator_gazebo/Tutorials/SpawningObjectInSimulation
